### ISSUE TITLE
local monogDB server to store annotated variants

### ISSUE THREAD

**Issue by patmagee** [BaderLab/GenomeClinic-PGX#5]
In order to begin production of for the pharmacogenomics app as well as the discovery app we need to run a local instance of a mongoDB that can store annotated variant information in a queryable manner. The database should have individual tables for projects that contain a foreign key to point to a patient table. Each patient will receive a separate table to store their variants. Multiple projects can point to the same patient.

Specific points of this are:
1. Create a module to store variants within a mongoDB
2. Annotate using annovar with the following annotations:
   a. ljb26_all
   b. cg69
   c. esp65000_all
   d. 1000G2014-sep
   e. CGD
   f. clinvar
3. Extract all annotations
4. Store Annotations
5. Write functions to enable easy query ability for annotated variants.

**Comment by keypanqi** [comment]
Hi,patmagee ~
I cannot download some annotation database(ljb26_all and  1000G2014-sep) with the command
perl annotate_variation.pl -buildver hg19 -downdb -webfrom annovar ljb26_all annovar_db/ .
Could you tell me ,why couldn't  I  and how did you download them~
I will appreciate ,if you can send these files (ljb26_all and  1000G2014-sep) to me.
Here is ,my email: 1053095150@qq.com.
